package com.phairplay

/**
 * BuildConfig stub for JVM test compilation.
 *
 * The real BuildConfig is generated by AGP (buildFeatures.buildConfig = true). This stub
 * only needs to declare the fields PhairPlay's production code reads, so that the
 * AGP-free test-runner module can compile those sources.
 *
 * Keep the values boring: tests assert on behaviour, not on version numbers. If a test
 * ever needs a specific version, inject it rather than editing these constants.
 */
object BuildConfig {
    const val CAST_APP_ID = ""

    /** GitHub repo the in-app updater polls ("owner/name"). */
    const val UPDATE_REPO = "2archiver/phairplay-archiver-fork-"

    /** Installed version code — compared against the versionCode of published releases. */
    const val VERSION_CODE = 1

    /** Installed version name. */
    const val VERSION_NAME = "test"
}
